autoreport: Fixes for enable_cpufreq
We got some failures on systems without CPB. The cpb sysfs interface
always exists, even on CPUs without core boosting support. Because
of this, we got "failed to set requested boost state" on systems
without core boosting support.

To fix this, we now return early on systems without core boosting
support. Additionally, search for the cpb interfaces on all CPUs,
not only CPU 0.

Signed-off-by: Frank Arnold <frank.arnold@amd.com>

diff --git a/tapper-autoreport b/tapper-autoreport
--- a/tapper-autoreport
+++ b/tapper-autoreport
@@ -617,18 +617,17 @@ enable_cpufreq () {
     done
 
     # Set requested boost state
-    if [ -f /sys/devices/system/cpu/cpufreq/boost ]; then
+    if ! has_cpufeature cpb; then
+        return $_SUCCESS
+    elif [ -f /sys/devices/system/cpu/cpufreq/boost ]; then
         interfaces="/sys/devices/system/cpu/cpufreq/boost"
-    elif [ -f /sys/devices/system/cpu/cpu0/cpufreq/cpb ]; then
+    elif [ $(ls /sys/devices/system/cpu/cpu*/cpufreq/cpb 2>/dev/null | wc -l) -gt 0 ]; then
         interfaces="/sys/devices/system/cpu/cpu*/cpufreq/cpb"
-    elif has_cpufeature cpb; then
-        if grep -q " show_cpb\| show_global_boost" /proc/kallsyms; then
-            echo "failed to find sysfs boost state interface"
-        elif [ $booststate -eq 0 ]; then
-            echo "cpufreq driver doesn't provide sysfs boost state interface"
-        else
-            return $_SUCCESS
-        fi
+    elif grep -q " show_cpb\| show_global_boost" /proc/kallsyms; then
+        echo "failed to find sysfs boost state interface"
+        return $_FAILURE
+    elif [ $booststate -eq 0 ]; then
+        echo "cpufreq driver doesn't provide sysfs boost state interface"
         return $_FAILURE
     else
         return $_SUCCESS
